---
title: "model-performance-rpart"
author: "Murugesan Nagarajan"
date: "4/16/2018"
output: html_document
---
## Initial Analysis

Read the data from csv file and separate the data as traininig and test data using 80:20 ratio. Grow the tree using the training data set

```{r eval=TRUE}
raw_data <- read.csv('/Projects/R/CSX415-project/phone_mark/data/bank.csv',sep=';')
ind <- sample(2,nrow(raw_data), replace = TRUE, prob = c(0.8,0.2))
train_data <- raw_data[ind==1,]
test_data <- raw_data[ind==2,]
library(rpart)
treemodel <- rpart(y~ age + job + marital + education + default + balance + housing + loan + contact + duration + campaign + pdays + previous + poutcome, data = train_data)
plotcp(treemodel)

```
Plot the Tree
```{r eval=TRUE}
plot(treemodel,uniform=TRUE,main="Classification tree for product subscription")
text(treemodel,use.n=TRUE,all=TRUE,cex=.8)
summary(treemodel)
```
# Performance evaluation

```{r eval=TRUE}
predi=predict(treemodel,train_data,type="class")
summary(predi)
table(predi,train_data$y)
```
Confusion matrix
```{r eval=TRUE}
table(predi,train_data$y)
```

Find the test accuracy

```{r eval=TRUE}
sum(diag(table(predi,train_data$y)))/length(train_data$y)
```
# Conclusion

The accuracy of the test data is over 91% by using the rpart model




