---
title: "model-performance-linear"
author: "Murugesan Nagarajan"
date: "4/16/2018"
output: html_document
---

```{r eval=TRUE}
library("caret")

raw_data <- read.csv('/Projects/R/CSX415-project/phone_mark/data/bank.csv',sep=';')
str(raw_data)
#ind <- sample(2,nrow(raw_data), replace = TRUE, prob = c(0.8,0.2))
#train_data <- raw_data[ind==1,]
#test_data <- raw_data[ind==2,]

#glmmodel <- glm(y~ age + job + marital + education + default + balance + housing + loan + contact + #duration + campaign + pdays + previous + poutcome, data = train_data,family=binomial)
#print(glmmodel)

```

```{r eval=TRUE}
index<-createDataPartition(raw_data$y,p=0.5,list=FALSE)
trainset<- raw_data[index,]
testset<-raw_data[-index,]



```
# Future selection using caret

```{r eval=TRUE}

str(trainset)
#control<-rfeControl(functions = rfFuncs,method="repeatedcv",repeats=3,verbose=FALSE)
outcomeName<-'y'
predictors<-names(trainset)[!names(trainset) %in% outcomeName]
#loan_pred_profile<-rfe(trainset[,predictors],trainset[,outcomeName],rfeControl = control)
#loan_pred_profile

```

# Training model using Caret
Apply GBM, Random forest, Neural Net and Logistic Regression

```{r eval=TRUE}
model_gbm<-train(trainset[,predictors],trainset[,outcomeName],method='gbm')
model_rf<-train(trainset[,predictors],trainset[,outcomeName],method='rf')
model_nnet<-train(trainset[,predictors],trainset[,outcomeName],method='nnet')
model_glm<-train(trainset[,predictors],trainset[,outcomeName],method='glm')
```

# Prediction using Caret package



```{r eval=TRUE}
#model_gbm<-train(trainset[,predictors],trainset[,outcomeName],method='gbm')
model_rf<-train(trainset[,predictors],trainset[,outcomeName],method='rf')
#model_nnet<-train(trainset[,predictors],trainset[,outcomeName],method='nnet')
#model_glm<-train(trainset[,predictors],trainset[,outcomeName],method='glm')
```
# Prediction
Evaluate the random forest model using the metrics

```{r eval=TRUE}
predict<-predict.train(object=model_rf,testset[,predictors],type="raw")
table(predict)
confusionMatrix(predict,testset[,outcomeName])
```
evaluate the GBM model and find the metrics

```{r eval=TRUE}
predict<-predict.train(object=model_gbm,testset[,predictors],type="raw")
table(predict)
confusionMatrix(predict,testset[,outcomeName])
```
evaluate the Neural Net model and calculate the metrics.
```{r eval=TRUE}
predict<-predict.train(object=model_nnet,testset[,predictors],type="raw")
table(predict)
confusionMatrix(predict,testset[,outcomeName])
```

evaluate the glm and calculate the metrics.
```{r eval=TRUE}
predict<-predict.train(object=model_glm,testset[,predictors],type="raw")
confusionMatrix(predict,testset[,outcomeName])
```
