---
title: "Model Performance"
author: "Murugesan Nagarjan"
date: "April 17, 2018"
output: html_document
---

## Initial Analysis

Bank ABC's marketing department markets Bank products like Checking account, saving account, term deposit and Loan products to their customers. As part of this marketing calls, the marketing team contact various people and gather initial information about the customer and store them in a call history database. The database has the past call history and details about how many such a call turned into potential buyer.

The team has around 2 years' worth of call history and the outcome details whether a customer turned into buyer or not. The department director complained that the team is spending lot of effort on making this phone call campaign, but very little prospect become clients for them. He wanted improve the no of sales target.

## Training data per

Call:
 randomForest(formula = y ~ age + job + marital + education +      default + balance + housing + loan + contact + duration +      campaign + pdays + previous + poutcome, data = train_data) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 3

        OOB estimate of  error rate: 10.66%
Confusion matrix:

pred |no| yes |class.error
-----|--|-----|-----------
no   |3123|  84|   0.0261927
yes  |303 | 119|   0.7180095


We can see that 500 trees were build, and the model randomly sampled 3 predictors at each split. It also shows a matrix containing prediction vs actual, as well as classification error for each class.

Calcualted the training accuracy using this confusion matrix and the accuracy is 89.76%

## Testing model performance

Predicted the target using the testing data set which is 20% of the entire data set and then computed the confusion matrix.

Test data confusion matrix

pred  | no |yes
----- |----|----
  no  |798 |76
  yes |29  |34
  
The accuracy of the testing data set is   88.79%

We have achieved more than 88% accuracy with very simple model. It could be further improved by feature selection,and possibly by trying different


